---
apiVersion: v1
kind: ConfigMap
metadata:
  name: atst-worker-envvars
  namespace: atat
data:
  AZURE_ACCOUNT_NAME: atat
  AZURE_TO_BUCKET_NAME: task-order-pdfs
  CAC_URL: https://auth-staging.atat.code.mil/login-redirect
  CELERY_DEFAULT_QUEUE: celery-master
  DEBUG: "0"
  DISABLE_CRL_CHECK: "true"
  MAIL_PORT: "587"
  MAIL_SENDER: postmaster@atat.code.mil
  MAIL_SERVER: smtp.mailgun.org
  MAIL_TLS: "true"
  OVERRIDE_CONFIG_DIRECTORY: /config
  PGAPPNAME: atst
  PGDATABASE: staging
  PGHOST: atat-db.postgres.database.azure.com
  PGPORT: "5432"
  PGSSLMODE: verify-full
  PGSSLROOTCERT: /opt/atat/atst/ssl/pgsslrootcert.crt
  PGUSER: atat_master@atat-db
  REDIS_HOST: atat.redis.cache.windows.net:6380
  REDIS_TLS: "true"
  SERVER_NAME: azure.atat.code.mil
  TZ: UTC
